variables:
    PLUGIN_NAME: 'authorAndSectionSearchFilters'
    
include:
  - project: 'documentacao-e-tarefas/modelosparaintegracaocontinua'
    ref: main
    file:
      - 'templates/groups/pkp_plugin.yml'
      - 'templates/groups/ojs/cypress_tests.yml'

